WebApplication4/Models/DBClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication4.Models
{
    public class DBClass
    {

        static DemoEntities D = new DemoEntities();
        public static List<EMPDATA> getEmp()
        {
            var E = from E1 in D.EMPDATAs
                    select E1;
            return E.ToList(); 
        }
        public static EMPDATA getEmpdata(int eno)
        {
            var E = from E1 in D.EMPDATAs
                    where E1.EMPNO==eno
                    select E1;
            return E.First();
        }
    }
}

WebApplication4/Models/EMPDATA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPDATA
    {
        public int EMPNO { get; set; }
        public string ENAME { get; set; }
        public string JOB { get; set; }
        public Nullable<int> MGR { get; set; }
        public Nullable<System.DateTime> HIREDATE { get; set; }
        public Nullable<int> SAL { get; set; }
        public Nullable<int> COMM { get; set; }
        public Nullable<int> DEPTNO { get; set; }
    }
}

WebApplication4/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities : DbContext
    {
        public DemoEntities()
            : base("name=DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPDATA> EMPDATAs { get; set; }
    }
}

WebApplication4/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Admin\source\repos\WebApplication4\WebApplication4\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

WebApplication4/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

WebApplication4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication4/Controllers/SampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class SampleController : Controller
    {
        // GET: Sample
        public ActionResult Index()
        {
            List<EMPDATA>L=   DBClass.getEmp();

            return View(L);
        }
        public ActionResult ExtractEmp()
        {
            int Eno = int.Parse(Request.Form["rdbEmp"].ToString());
            EMPDATA E = DBClass.getEmpdata(Eno);
            return View(E);
        }
        public ActionResult Index1()
        {
            ViewBag.L = DBClass.getEmp();

            return View();
        }
        public ActionResult ExtractEmp1()
        {
            int Eno = int.Parse(Request.Form["rdbEmp"].ToString());
            ViewBag.E = DBClass.getEmpdata(Eno);
            return View();
        }
        public ActionResult Index2()
        {
            List<EMPDATA> L = DBClass.getEmp();

            return View(L);
        }
        public ActionResult ExtractEmp2()
        {
            int Eno = int.Parse(Request.QueryString["E"].ToString());
            EMPDATA E = DBClass.getEmpdata(Eno);
            return View(E);
        }
    }
}

WebApplication4/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication4/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication4/Views/Sample/ExtractEmp.cshtml
@model WebApplication4.Models.EMPDATA
@{
    ViewBag.Title = "ExtractEmp";
}

<h2>ExtractEmp</h2>
@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>Empno</td>
            <td>@Html.TextBoxFor(a => a.EMPNO)</td>
        </tr>
        <tr>
            <td>Ename</td>
            <td>@Html.TextBoxFor(a => a.ENAME)</td>
        </tr>
        <tr>
            <td>Job</td>
            <td>@Html.TextBoxFor(a => a.JOB)</td>
        </tr>
        <tr>
            <td>Mgr id</td>
            <td>@Html.TextBoxFor(a => a.MGR)</td>
        </tr>
        <tr>
            <td>HIREDATE</td>
            <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
        </tr>
        <tr>
            <td>Salary</td>
            <td>@Html.TextBoxFor(a => a.SAL)</td>
        <tr>
            <td>Comm</td>
            <td>@Html.TextBoxFor(a => a.COMM)</td>
        </tr>

        <tr>
            <td>Deptno</td>
            <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
        </tr>


    </table>
}


}

WebApplication4/Views/Sample/ExtractEmp1.cshtml
@{
    ViewBag.Title = "ExtractEmp";
}

<h2>ExtractEmp</h2>
@using (Html.BeginForm())
{
    if (ViewBag.E != null)
    {
        <table>
            <tr>
                <td>Empno</td>
                <td>@Html.TextBox("EMPNO",(object)ViewBag.E.EMPNO)</td>
            </tr>
            <tr>
                <td>Ename</td>
                <td>@Html.TextBox("ENAME",(object)ViewBag.E.ENAME)</td>
            </tr>
            <tr>
                <td>Job</td>
                <td>@Html.TextBox("JOB",(object)ViewBag.E.JOB)</td>
            </tr>
            <tr>
                <td>Mgr id</td>
                <td>@Html.TextBox("MGR",(object)ViewBag.E.MGR)</td>
            </tr>
            <tr>
                <td>HIREDATE</td>
                <td>@Html.TextBox("HD",(object)ViewBag.E.HIREDATE)</td>
            </tr>
            <tr>
                <td>Salary</td>
                <td>@Html.TextBox("SAL",(object)ViewBag.E.SAL)</td>
            <tr>
                <td>Comm</td>
                <td>@Html.TextBox("COMM",(object)ViewBag.E.COMM)</td>
            </tr>

            <tr>
                <td>Deptno</td>
                <td>@Html.TextBox("DEPTNO",(object)ViewBag.E.DEPTNO)</td>
            </tr>


        </table>
    }


}

WebApplication4/Views/Sample/ExtractEmp2.cshtml
@model WebApplication4.Models.EMPDATA
@{
    ViewBag.Title = "ExtractEmp";
}

<h2>ExtractEmp</h2>
@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>Empno</td>
            <td>@Html.TextBoxFor(a => a.EMPNO)</td>
        </tr>
        <tr>
            <td>Ename</td>
            <td>@Html.TextBoxFor(a => a.ENAME)</td>
        </tr>
        <tr>
            <td>Job</td>
            <td>@Html.TextBoxFor(a => a.JOB)</td>
        </tr>
        <tr>
            <td>Mgr id</td>
            <td>@Html.TextBoxFor(a => a.MGR)</td>
        </tr>
        <tr>
            <td>HIREDATE</td>
            <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
        </tr>
        <tr>
            <td>Salary</td>
            <td>@Html.TextBoxFor(a => a.SAL)</td>
        <tr>
            <td>Comm</td>
            <td>@Html.TextBoxFor(a => a.COMM)</td>
        </tr>

        <tr>
            <td>Deptno</td>
            <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
        </tr>


    </table>
}


}

WebApplication4/Views/Sample/Index.cshtml
@model IEnumerable<WebApplication4.Models.EMPDATA>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("ExtractEmp","Sample"))
{
<table>
    <tr>
        <td>Empno</td>
        <td>Ename</td>
        <td>Job</td>
        <td>Mgr</td>
        <td>HireDate</td>
        <td>Sal</td>
        <td>Comm</td>
        <td>Deptno</td>
    </tr>
    @if (Model != null)
    {
            foreach (var E in Model)
            { 
<tr>
    <td>@Html.RadioButton("rdbEmp", E.EMPNO)</td>
    <td>@E.EMPNO</td>
    <td>@E.ENAME</td>
    <td>@E.JOB</td>
    <td>@E.MGR</td>
    <td>@E.HIREDATE</td>
    <td>@E.SAL</td>
    <td>@E.COMM</td>
    <td>@E.DEPTNO</td>
</tr>
            }


    }



</table>
<input type="submit" />

}

WebApplication4/Views/Sample/Index1.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("ExtractEmp1", "Sample"))
{
    <table>
        <tr>
            <td>Empno</td>
            <td>Ename</td>
            <td>Job</td>
            <td>Mgr</td>
            <td>HireDate</td>
            <td>Sal</td>
            <td>Comm</td>
            <td>Deptno</td>
        </tr>
        @if (ViewBag.L!= null)
        {
            foreach (var E in ViewBag.L as IList<WebApplication4.Models.EMPDATA>)
            {
                <tr>
                    <td>@Html.RadioButton("rdbEmp", E.EMPNO)</td>
                    <td>@E.EMPNO</td>
                    <td>@E.ENAME</td>
                    <td>@E.JOB</td>
                    <td>@E.MGR</td>
                    <td>@E.HIREDATE</td>
                    <td>@E.SAL</td>
                    <td>@E.COMM</td>
                    <td>@E.DEPTNO</td>
                </tr>
            }


        }



    </table>
    <input type="submit" />

}

WebApplication4/Views/Sample/Index2.cshtml
@model IEnumerable<WebApplication4.Models.EMPDATA>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>Empno</td>
            <td>Ename</td>
            <td>Job</td>
            <td>Mgr</td>
            <td>HireDate</td>
            <td>Sal</td>
            <td>Comm</td>
            <td>Deptno</td>
        </tr>
        @if (Model != null)
        {
            foreach (var E in Model)
            {
                <tr>
                    <td>@Html.RadioButton("rdbEmp", E.EMPNO, new { onclick = "func(this.value);" })</td>
                    <td>@E.EMPNO</td>
                    <td>@E.ENAME</td>
                    <td>@E.JOB</td>
                    <td>@E.MGR</td>
                    <td>@E.HIREDATE</td>
                    <td>@E.SAL</td>
                    <td>@E.COMM</td>
                    <td>@E.DEPTNO</td>
                </tr>
            }


        }



    </table>
   

}
<script>
    function func(eno)
    {
        alert(eno);
        window.location.href = "/Sample/ExtractEmp2?E=" + eno;

    }




</script>

WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>